apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
spec:
  selector:
    matchLabels:
      app: scaletestapp
  replicas: 1
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: shestera/scaletestapp
          resources:
            requests:
              cpu: "10m"
              memory: "10Mi"
            limits:
              cpu: "20m"
              memory: "30Mi"
          ports:
            - containerPort: 8080
