apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
    prometheus-monitored: "true"
spec:
  type: NodePort
  selector:
    app: scaletestapp
  ports:
    - protocol: TCP
      port: 8080
